/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Auth/ConfirmPassword': RouteRecordInfo<'/Auth/ConfirmPassword', '/Auth/ConfirmPassword', Record<never, never>, Record<never, never>>,
    '/Auth/ForgotPassword': RouteRecordInfo<'/Auth/ForgotPassword', '/Auth/ForgotPassword', Record<never, never>, Record<never, never>>,
    '/Auth/Login': RouteRecordInfo<'/Auth/Login', '/Auth/Login', Record<never, never>, Record<never, never>>,
    '/Auth/Register': RouteRecordInfo<'/Auth/Register', '/Auth/Register', Record<never, never>, Record<never, never>>,
    '/Auth/ResetPassword': RouteRecordInfo<'/Auth/ResetPassword', '/Auth/ResetPassword', Record<never, never>, Record<never, never>>,
    '/Auth/VerifyEmail': RouteRecordInfo<'/Auth/VerifyEmail', '/Auth/VerifyEmail', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Profile/Edit': RouteRecordInfo<'/Profile/Edit', '/Profile/Edit', Record<never, never>, Record<never, never>>,
    '/Profile/Partials/DeleteUserForm': RouteRecordInfo<'/Profile/Partials/DeleteUserForm', '/Profile/Partials/DeleteUserForm', Record<never, never>, Record<never, never>>,
    '/Profile/Partials/UpdatePasswordForm': RouteRecordInfo<'/Profile/Partials/UpdatePasswordForm', '/Profile/Partials/UpdatePasswordForm', Record<never, never>, Record<never, never>>,
    '/Profile/Partials/UpdateProfileInformationForm': RouteRecordInfo<'/Profile/Partials/UpdateProfileInformationForm', '/Profile/Partials/UpdateProfileInformationForm', Record<never, never>, Record<never, never>>,
    '/Welcome': RouteRecordInfo<'/Welcome', '/Welcome', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'resources/js/pages/index.vue': {
      routes: '/'
      views: never
    }
    'resources/js/pages/Auth/ConfirmPassword.vue': {
      routes: '/Auth/ConfirmPassword'
      views: never
    }
    'resources/js/pages/Auth/ForgotPassword.vue': {
      routes: '/Auth/ForgotPassword'
      views: never
    }
    'resources/js/pages/Auth/Login.vue': {
      routes: '/Auth/Login'
      views: never
    }
    'resources/js/pages/Auth/Register.vue': {
      routes: '/Auth/Register'
      views: never
    }
    'resources/js/pages/Auth/ResetPassword.vue': {
      routes: '/Auth/ResetPassword'
      views: never
    }
    'resources/js/pages/Auth/VerifyEmail.vue': {
      routes: '/Auth/VerifyEmail'
      views: never
    }
    'resources/js/pages/Dashboard.vue': {
      routes: '/Dashboard'
      views: never
    }
    'resources/js/pages/Profile/Edit.vue': {
      routes: '/Profile/Edit'
      views: never
    }
    'resources/js/pages/Profile/Partials/DeleteUserForm.vue': {
      routes: '/Profile/Partials/DeleteUserForm'
      views: never
    }
    'resources/js/pages/Profile/Partials/UpdatePasswordForm.vue': {
      routes: '/Profile/Partials/UpdatePasswordForm'
      views: never
    }
    'resources/js/pages/Profile/Partials/UpdateProfileInformationForm.vue': {
      routes: '/Profile/Partials/UpdateProfileInformationForm'
      views: never
    }
    'resources/js/pages/Welcome.vue': {
      routes: '/Welcome'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
